- demo/data/outcomes/level-1.json
- demo/data/outcomes/level-2.json
- demo/data/outcomes/level-3.json
- demo/data/outcomes/suggested-level.json
- demo/index.html
- package-lock.json
- package.json
Here is a demo of the d2l-outcomes-level-of-achievements component. It appears to be responsive to the sidebar changing sizes. The data structure for it is fairly simple. There is just an array of options with text and colors, then a suggested text above that.
> d2l-outcomes-level-of-achievements demo

- .travis.yml
trying to figure out why frau-ci isn't auto-releasing after a merge
for this specific PR, the `-d` flag is already specified in the travis variable `DEFAULT_INCREMENT` so it was redundant
> default increment is already specified

- .travis.yml
I think BSI only looks for releases and not just tags so adding this code from `activities` to auto release on tagged builds.
> Get travis to auto release on tagged builds

- .travis.yml
This PR is for breaking the build into stages so that it will work with the visual difference bot. This is a prerequisite to setting up the bot.
Once this PR is approved, someone with the proper authorization for `BrightspaceHypermediaComponents` as an `"owner"` can install the bot by following **step one** [here](https://github.com/BrightspaceUI/visual-difference-bot/blob/master/README.md#setting-up-the-bot-on-your-existing-brightspace-repo). @AlexBedley I think you should have permissions since you created the repo.
> updating travis.yml to include build stages

- components/footer/consistent-evaluation-footer.js
This is so that the controller is instantiated before the render function is called.
> Changing footer controller instantiation to use setters and getters

- components/left-panel/consistent-evaluation-submission-item.js
context:
BrightspaceUI/core#681
This updates the slot name secondary so supporting-info
> Update slot name to supporting-info

- components/consistent-evaluation-page.js
- components/consistent-evaluation.js
- components/controllers/constants.js
- components/left-panel/consistent-evaluation-submission-item.js
- components/left-panel/consistent-evaluation-submissions-page.js
- components/right-panel/consistent-evaluation-grade-result.js
- components/right-panel/consistent-evaluation-right-panel.js
Consolidated naming convention best practices and a working consistent eval app.
For _strings_ and _bools_, pass using **attributes**:
`some-attribute`
`?some-bool`
For _objects_, pass using **property** bindings:
`.someProperty`
> change to proper property and attribute binding

- components/consistent-evaluation-page.js
- components/right-panel/consistent-evaluation-feedback-presentational.js
- components/right-panel/consistent-evaluation-right-panel.js
This is the unfortunate way that the html editor needs to work. It cant be initialized with a value twice. So the first time we init it, we set it to undefined now. Then when we actually have text, we set it to a value.
> pass undefined when the feedback text is not defined

- components/left-panel/consistent-evaluation-submission-item.js
This should fix the issue where the menu button click was also opening an attachment in evidence view
https://rally1.rallydev.com/#/detail/userstory/407933700552?fdp=true
> move @click to content to expose menu button

- components/left-panel/consistent-evaluation-submission-item.js
Get rid of the empty href on `d2l-list` that was to make hover state text styling appear, to be able to access `d2l-list-content` click handling.
> get rid of href to access list-content click

- .stylelintrc.json
- components/footer/consistent-evaluation-footer-presentational.js
- components/left-panel/consistent-evaluation-evidence-file.js
- components/left-panel/consistent-evaluation-evidence-text.js
- components/left-panel/consistent-evaluation-evidence-top-bar.js
- components/left-panel/consistent-evaluation-left-panel.js
- components/left-panel/consistent-evaluation-submission-item.js
- components/left-panel/consistent-evaluation-submissions-page.js
- components/right-panel/consistent-evaluation-feedback-actions.js
- components/right-panel/consistent-evaluation-right-panel-block.js
- components/right-panel/consistent-evaluation-right-panel.js
- package-lock.json
- package.json
Added cool 3rd-party linting tool for styles embedded in HTML, markdown, JS, and most conveniently, template literals.
Rules are imported from @brightspace-ui/stylelint-config
This will hopefully keep consistent linting of styles in our components.
For more information view this blog post: https://blog.d2l.dev/2020/08/04/style-linting/
Example output (npm run lint):
> Add StyleLint to make styling more consistent

- test/perceptual/consistent-evaluation-right-panel.visual-diff.js
- test/perceptual/consistent-evaluation.visual-diff.js
Some tests were skipped and needed to be checked for the addition of StyleLint changes
> Remove .skip from visualdiff tests

- components/left-panel/consistent-evaluation-submission-item.js
- use the getFileIconTypeFromExtension that was added to core/icons
- use the extension property now returned by the API for file attachment
- re-add in the text submission view that somehow got erased (probably because of me not merging master to a prev branch frequently enough 😿 )
Note: no UI changes!
> US119141: Use new property provided by the API to determine file type

- components/consistent-evaluation-page.js
- components/consistent-evaluation.js
- components/header/consistent-evaluation-nav-bar.js
- package-lock.json
- test/perceptual/consistent-evaluation-header-nav-bar.visual-diff.js
The navbar now accepts the `return-href` to the previous page and navigates back when clicked.
In the case where there's no `return-href` provided, the backbutton is not rendered:
It is also ready to receive the back-button text for when that is added to the API. (i.e. text = Submissions)
In the case where no text is received but the `return-href` is present, Back is defaulted.
> Add functionality to navbar back button

- components/left-panel/consistent-evaluation-evidence-file.js
We just forgot to make it https when we originally made this file (couldn't test it since we didn't have a version until now)
> Fix expected annotations viewer host

- components/left-panel/consistent-evaluation-submission-item.js
- components/left-panel/consistent-evaluation-submissions-page.js
Related to [US120545](https://rally1.rallydev.com/#/294005552584d/custom/236803223728?detail=%2Fuserstory%2F435781871716)
Fixed issue where iterating through students, all evidence for the students would append onto the submissions list. Did this by clearing the list of submissions when initializing the submission entity.
Also fixed a bug where the comments would not update.
> Fix submission list appending when iterating through students

- components/consistent-evaluation-page.js
Problem: when iterating between students, transiently saved state (such as text feedback) should not be persisted. To reproduce:
1. change text feedback from `"good"` to `"not good"`
2. iterate to next student
3. iterate back to previous student
expected: feedback is `"good"`
actual: feedback is `"not good"`
Solution: What's going on here is EntityStore is caching our transiently saved state (the `"not good"`). So when we hit that cache we're getting the "dirty" value. So we simply bypass the cache and go straight to the API when loading `consistent-evaluation-page`. The tradeoff for this correctness is performance, now we must load fresh each time we iterate (previously if we iterated backwards to something we'd already seen, it would just load what it had from cache).
> Do not use cache when loading entity in consistent-evaluation-page

- components/left-panel/consistent-evaluation-left-panel.js
It was really just a timing problem, the error would resolve on the 2nd draw once the submission list object is defined, but will remove the original error from the console now
> - Fixing submission info console error

- .travis.yml
15.0.0 is causing npm ci issues
> lock node version in travis (for now)

- components/consistent-evaluation.js
Problem: Launching files directly was broken after the files refactor. Digging into it, the problem is the initial load code and the subsequent load code (ie after iteration) are the same. We want to show submissions view after iteration, but not necessarily after the initial load (in the case of direct file launch). 
Solution: I just added another property (`currentFileId`) to pass the file id down and used the original `fileId` property as a flag to determine if this is the first load or not. This also has the advantage of not messing with the browser history stack after every iteration.
> Only load file and strip url the initial load

- components/left-panel/consistent-evaluation-outcomes-overall-achievement.js
- package.json
On the COA eval page in the LMS, the left panel contents had no whitespace. Per desired specs, this adds vertical margins of 36px and horizontal margins of either 12px or 18px depending on the viewport width of the panel.
> Add whitespace margins to COA primary panel

- components/controllers/ConsistentEvaluationHrefController.js
- components/controllers/constants.js
The COA achievements selector does not show up if there is no initial evaluated checkpoint demonstration. We can instead get the demonstration from the linked Alignments entity.
https://rally1.rallydev.com/#/detail/defect/449083112472?fdp=true
> DE41070 - Show COA achievements selector on right panel

- components/consistent-evaluation-page.js
- components/controllers/ConsistentEvaluationController.js
- components/controllers/ConsistentEvaluationHrefController.js
- components/controllers/constants.js
- components/right-panel/consistent-evaluation-feedback-presentational.js
- components/right-panel/consistent-evaluation-right-panel.js
- demo/consistent-evaluation-feedback.html
- demo/data/grade/attachments.json
- demo/data/grade/evaluationEntity.json
Don't want attachments in right panel for COA eval.
Goes along with this API change: https://github.com/Brightspace/lms/pull/2746
> Make attachments only appear if supported

- components/right-panel/consistent-evaluation-attachments-editor.js
Problem:  When you attach a file and then publish or save draft the attached file is removed from the ui (its saved correctly)
Solution: No longer hit the cache when fetching file attachments
I think this is an easy fix, but exposes some issues with our overall design.  Ideally we don't re-fetch the attachment list after publish since we already know what is attached.
> Bypassing cache when fetching attachments

- components/consistent-evaluation-page.js
- components/controllers/ConsistentEvaluationController.js
Related: https://github.com/Brightspace/outcomes-level-of-achievement-ui/pull/58
Unlike the achievements selector in the `consistent-evaluation-outcomes` component, the achievements selector in the `coa-eval-override` component does not autosave, and fires an event with the corresponding "select" action instead.
Changes:
* Add a listener when an outcome in `coa-eval-override` is selected which "unsaves" the evaluation
* Prior to saving/updating/publishing an evaluation, publish the COA demonstration (if applicable)
This should not change any functionality in any tool other than in Mastery View.
> Save coa-eval-override component prior to publishing evaluation

- components/right-panel/consistent-evaluation-right-panel.js
Should not be initialized as null. When left uninitialized instead, will have the value undefined and will
not insert 'null' as invalid href string
> Fix hidden feedback attachments

- components/header/consistent-evaluation-nav-bar.js
Changes the title of the middle navbar segment to be marked up as a heading, allowing screen reader users to quickly navigate to it. Also fixes the application of the d2l-heading-3 typography style to this title.
> Navbar title style + markup

- components/controllers/ConsistentEvaluationController.js
In the COA Manual Override page, when only publishing feedback with an achievement selector, the evaluation fails to publish since publish action is null and there is no nullcheck.
Changes:
* Add a nullcheck to `publishAction` in saveCoaDemonstration
> Nullcheck COA publish action

- components/header/d2l-consistent-evaluation-lcb-user-context.js
[US122306](https://rally1.rallydev.com/#/detail/userstory/455120973556?fdp=true): A11y - Use of Headers
So essentially we want 3 items on the page to have heading levels assigned:
- Assignment Name = 1
- Student Name = 2
- Submission Name = 3
This PR just adds level 2 to student name.
Jamie M previously added level 1 to assignment name, 3 days ago: https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/commit/253f4e1a30164ccf8c96cdc5ee7f7400c6801f26#diff-580e82674cf3dc7a9b4cea996e56e70d7f5762ef61dca744ba8e7e42aa0924e3R178
And level 3 was already on submission name: 
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/blob/master/components/left-panel/consistent-evaluation-submission-item.js#L268 …
> make student name heading level 2

- components/consistent-evaluation-page.js
- components/header/d2l-consistent-evaluation-lcb-file-context.js
As promised, here's follow up 2 from the previous PR. This adds a super hacky way of keeping the file selector in-sync with the currently selected file. The problem is the UI change of selecting a different file changes the UI state, but since the `currentFileId` does not change, Lit does not re-render. Thus we need to manually tell it "hey actually we need you to display the file that corresponds to your `currentFileId`"
> Add in not great way to refresh the file selector after a declined discard of annotations

- components/consistent-evaluation-page.js
- components/controllers/ConsistentEvaluationController.js
These 3 PRs are related to each other:
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/181
https://github.com/Brightspace/outcomes-level-of-achievement-ui/pull/64
https://github.com/Brightspace/d2l-outcomes-overall-achievement/pull/59
Recently, the COA `publish` action now has a field that requires knowledge of the state of the COA component and the feedback contents. As a result, the `publish` action is now moved to the COA component itself and is called using the `d2l-save-evaluation` event.
Changes:
* Remove any COA-related logic in the `ConsistentEvaluationController`
* Pass in the evaluation entity to the `d2l-save-evaluation` event for the COA component to use for its `publish` action.
https://rally1.rallydev.com/#/detail/defect/455925703800?fdp=true
> Remove COA demonstration entity from controller

- components/consistent-evaluation-page.js
- components/transient-save-awaiter.js
- test/transient-save-awaiter.test.js
Related: https://github.com/Brightspace/outcomes-level-of-achievement-ui/pull/65
The transient-saving Siren action in the `coa-eval-override` right-hand component is in the component itself, so it isn't mutexed in consistent-eval. Thus, performing the `publish` action before the transient-saving action to finish causes the component to not save correctly.
Changes:
* Add a `_savePromises` array to `consistent-evaluation-page` and await those promises prior to performing any `publish` action
* Modify `transientSaveCoaEvalOverride` to add its `performSirenAction` promise to the promise array
https://rally1.rallydev.com/#/detail/defect/458210498988?fdp=true
> Add promise array to consistent-eval-page

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .travis.yml
- README.md
- karma.sauce.conf.js
- package-lock.json
- package.json
As discussed in Slack, this converts the Test & Release workflows from Travis CI -> GitHub Actions. @svanherk is still working on a visual-diff action, but I this can run in hybrid mode (most things in GHAs, Visual Diff in Travis) temporarily.
Look over the instructions in the README to make sure everything is clear. I've switched the default version increment from patch -> minor so that if you need to do a hotfix there are patch versions available. If that's not what you want, I can put it back.
For those hotfix releases, how do they normally work branch-wise? I'd recommend naming the branches something like `release/20.21.1` according to the Brightspace release, or `1.15.x` according to the consistent-eval version. Let me know so I can add that branch name regex into the release …
> Switch test & release to GitHub Actions

- demo/consistent-evaluation-coa-override-page-published.html
- demo/consistent-evaluation-coa-override-page.html
- demo/data/outcomes-overall-achievement/alignment.json
- demo/data/outcomes-overall-achievement/alignments.json
- demo/index.html
- package-lock.json
This focuses on the `consistent-evaluation-coa-override-page` demo page.
Changes:
* Add necessary data files for ConsistentEvaluationController to correctly get its data for `consistent-evaluation-coa-override-page`
* Remove `d2l-demo-snippet`, since it doesn't work well with the `position: absolute` property of `d2l-template-primary-secondary`
* Add another demo page for a published COA evaluation
This is what the demo page will look like:
> Fix COA demo page

- components/header/consistent-evaluation-nav-bar.js
- package-lock.json
[DE41679](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fdefect%2F463461237476&fdp=true?fdp=true): Translations - The text for User x of y in the navbar is wrapping with Japanese and Arabic languages
`2.5rem` fixes this for sufficiently large class sizes (665 of 665):
> reduce padding to ensure one line for all languages

- components/right-panel/consistent-evaluation-rubric.js
Talked to Dan and he liked the look of truncating the contents of the grading rubric like how we did it for the file-context-dropdown
> Fix truncating bug in grading rubric dropdown

- components/right-panel/consistent-evaluation-grade-result.js
When the grade is null, don't change it to 0. 
Note: this ticket won't have an effect until https://github.com/Brightspace/lms/pull/5582 is merged in as we currently never return null for a grade
> DE42030 Allow a default grade of null.

- components/consistent-evaluation-dialogs.js
- components/consistent-evaluation-page.js
My previous change seems to not allow users to update/publish twice in a row (because it didn't reset `isUpdateClicked`/`isPublishClicked` to false after an update). This fixes that!
> 122595 Fix to let users update/publish twice.

- components/consistent-evaluation-dialogs.js
- components/consistent-evaluation-page.js
as per the comment on https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/261, render dialogs programmatically.
> US124085 don't render multiple dialogs.

- components/controllers/ConsistentEvaluationHrefController.js
- test/ConsistentEvaluationHrefController.test.js
Instead of adding "hasUnscoredCriteria" to the api use whether the assessment entity has "complete" or "incomplete" class to determine whether the rubrics have unscored assessments
Note: Currently "incomplete" and "complete" are returned on a rubric incorrectly as noted in [this defect](https://rally1.rallydev.com/#/42960320374d/dashboard?Iteration=u&Name=&Project=%2Fproject%2F42960320374&Release=u&cpoid=42960320374&detail=%2Fdefect%2F489745544288&rankTo=BOTTOM&typeDef=7362609627) . There will be a partner PR in the backend to fix this that will also remove "hasUnscoredCriteria" from the backend.
> US122594/mbosilj use "incomplete" class.

- components/consistent-evaluation-dialogs.js
- lang/en.js
Talked to Dan, ok with using default d2l-dialog ('x' button has same behaviour as "Continue Grading"). Confirmation dialog was too narrow for the "Continue Grading" and "Publish Anyway" buttons, so using d2l-dialog insteacd. Dialog looks like:
> US122594/mbosilj Update dialog copy.

- components/left-panel/consistent-evaluation-submissions-page.js
This was caused because we weren't updating the submissionEntities in the front end after modifying them in the backend.
Note the other way I could think of solving this was to have the front end loop through and update all the attachments in the submissionEntities. I chose instead to make another API call since the other way felt like a lot of computation for the front end and so we could ensure we didn't get inconsistent data in the front/back end.
Let me know if we'd rather avoid this API call!
> US124534/mbosilj after download all sets files as read.

- components/header/consistent-evaluation-user-profile-card.js
- components/header/d2l-consistent-evaluation-lcb-user-context.js
- demo/consistent-evaluation-user-profile-card.html
- demo/index.html
- package-lock.json
- package.json
This is the initial implementation of the `user-profile-card`'s UI/responsiveness as we are not getting any data from the backend yet
When hovering over/clicking the `user-context` component, the `user-profile-card` is displayed
The `user-profile-card` disappears when the user navigates their cursor off the `user-profile-card`
Notes: 
There isn't an option to hide the online/offline status so for the current implementation it'll be forever offline
> Add user-profile-card to CE

- components/header/d2l-consistent-evaluation-lcb-user-context.js
Use item select to trigger group menu actions instead of onClick to capture both keyboard and mouse.
> Group Options menu keyboard accessibility

- components/consistent-evaluation-page.js
- components/header/d2l-consistent-evaluation-lcb-user-context.js
- components/header/d2l-consistent-evaluation-learner-context-bar.js
[US119337](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F412022776500&fdp=true?fdp=true): [UI] Make sure the username does not display when anonymous marking
The story description isn't entirely accurate as the designs indicate that we want to hide the entire card if the assignment is anonymous: https://d2lmail.sharepoint.com/:w:/r/sites/uxteam/_layouts/15/Doc.aspx?sourcedoc=%7B2001E110-38CE-4773-B7AA-19DDBC2E9235%7D&file=Anonymous%20Marking%20-%20Consistent%20Eval%20Specs.docx&action=default&mobileredirect=true
The rubrics popout already respects the anonymous name:
> Hide profile card if assignment is anonymous

- components/left-panel/consistent-evaluation-submission-item.js
- components/left-panel/consistent-evaluation-submissions-page.js
Fix for US124816/DE42623, stop button from appearing on profile card without impacting `More Options` menu
Giving the `Submissions List` it's own [Stacking Context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) stops the popups from appearing over top of the profile card.
> US124816/DE42623 Limit submission items menus to submission list context

- components/consistent-evaluation-page.js
Megan caught this - we need to await for the entire `_flushAndWait` block.
I confirmed the JS control flow logic with Alex. The code calling `_flushAndWait` will not wait for the inner `await` calls to finish before proceeding.
> await all calls to _flushAndWait

- components/right-panel/consistent-evaluation-grade-result.js
[DE42734](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fdefect%2F505877924612&fdp=true?fdp=true): Assignments > 20.21.03 > Dialog box A11y issues
As per suggestion by Dave B here: https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/109#discussion_r504909814
Please note this PR only fixed this issue from the defect: `when the dialog closes, the focus is at the top of the page not on the icon that was clicked, this makes it hard for a visually impaired user to know where they are and it take a lot of keystroke to get back to where they were.`
The point around dialogs closing with `esc` is to be done as part of a follow up story, as the logic is the same as in the old experience.
> use getComposedActiveElement

- components/left-panel/assignments/consistent-evaluation-submission-item.js
Note we might want to add a loading state to grade mark. I have the same loading behaviour as the similarity report: show grademark until the tii report is complete and then conditionally render it.
> DE42930/hide grademark if disabled.

- components/left-panel/assignments/consistent-evaluation-submission-item.js
This PR fixes an error thrown when the user tries to flag a text submission, or mark it as read. The error prevented the read/flagged status from being updated for text submissions.
> US124234: Fix error thrown when toggling 'read' or 'flagged' status for a text submission

- components/consistent-evaluation.js
When a student has only submitted 1 submission for an assignment, and that submission only has 1 attachment, the Assignment Evaluation page will automatically (on page load) open the attachment in the file viewer.
However, this should not happen for link attachments, which should always open in a new tab. Part of the reason is that when Audio/Video Note link attachments are opened in the file viewer, the Media Player will be shown inline. The Media Player currently has resizing and cutoff limitations inside of the file viewer, as shown below:
This PR prevents the file viewer from automatically opening if there is 1 submission with 1 link attachment. Instead, the submissions list will be shown.
> US124234: Prevent link attachments from opening in file viewer

- components/left-panel/assignments/consistent-evaluation-evidence-assignment.js
If the user is grading an assignment with the annotations viewer open and goes to the next student, this hides the annotation viewer and instead shows the submissions skeleton until the next students information loads.
> US127007/show left skeleton when iterating.

- components/consistent-evaluation-page.js
The issue was when a file is saved the file id changes so since the attachments aren't updated after a 'save-draft' if we try to remove the attachment, it uses the old file id (which doesn't correspond to any files)
> DE43176/update attachmentsInfo after saving draft.

- components/consistent-evaluation-page.js
- components/consistent-evaluation.js
- components/controllers/ConsistentEvaluationHrefController.js
- components/left-panel/consistent-evaluation-left-panel.js
- components/left-panel/discussions/consistent-evaluation-evidence-discussion.js
- test/ConsistentEvaluationHrefController.test.js
Note this currently doesn't do anything but when we eventually allow users to iterate between different discussion topics the filters should clear themselves
> US126243/clear filters if different discussionTopic.

- components/left-panel/discussions/consistent-evaluation-discussion-post-page.js
- lang/en.js
if no posts are displayed because none of them satisfy the filter this is shown. Note this is temporary until we have the table component, when we do there is an updated design that Fiona made!
> US126243/show card if all posts are filtered out.

- components/helpers/consistent-eval-telemetry.js
* As part of the PBMM work we need to ensure we do not log telemetry events for Protected B clients so the case where data telemetry endpoint could be `null` is more likely to happen now. Through testing, it's found that consistent-evaluation would throw a 500 POST error when that happens, this PR is aimed to fix that 500 error.
Related PR: https://github.com/Brightspace/lms/pull/10201
* When data telemetry endpoint is null, no network request is created to log the telemetry event
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F600523947568&fdp=true?fdp=true
> US127307 Added null check for data telemetry endpoint

- components/controllers/ConsistentEvaluationController.js
- components/header/d2l-consistent-evaluation-lcb-file-context.js
- components/header/d2l-consistent-evaluation-lcb-user-context.js
- components/left-panel/assignments/consistent-evaluation-evidence-assignment.js
- components/right-panel/consistent-evaluation-grade-result.js
- components/right-panel/consistent-evaluation-right-panel.js
- components/right-panel/consistent-evaluation-rubric.js
- package-lock.json
- package.json
This will remove the front end part of the logging, the back end part is already shipped. Things will now fail fairly organically and get caught by the uncaught exception logger when needed.
Have a read and let me know if we'd prefer throws in some places.
> clean up logging

- components/right-panel/consistent-evaluation-right-panel-block.js
Allows users to tab into the mobile drawer of CE and press `Enter` or `Space` to open the dialog
> Add tabindex and keyboard accessibility to mobile drawer

- components/consistent-evaluation-page.js
- components/left-panel/assignments/consistent-evaluation-tii-grade-mark.js
- components/right-panel/consistent-evaluation-right-panel.js
Missing isValidGrade event parameter was blocking transient grade save from happening (thanks Jamie :) )
> DE43869 - fixing overall score not updating for rubrics

- components/right-panel/consistent-evaluation-rubric.js
Allows the rubric statistics button from the old evaluation experience to be included, if a link is also provided by the API.
https://rally1.rallydev.com/#/57732444928d/dashboard?detail=%2Fuserstory%2F508482042404
> feat: Set include-statistics attribute for inline rubric

- components/consistent-evaluation-page.js
- components/consistent-evaluation.js
- components/right-panel/consistent-evaluation-right-panel.js
- components/right-panel/consistent-evaluation-rubric.js
Rally: [US129073](https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F601565647541)
Enables toggling between the inline grading revamp and the legacy experience via the `useInlineGradingRevamp` attribute on `<d2l-consistent-evaluation>`. See [Brightspace/lms#11459](https://github.com/Brightspace/lms/pull/11459) and [Brightspace/d2l-rubric#816](https://github.com/Brightspace/d2l-rubric/pull/816) for more details.
> feat: add rubrics inline grading revamp toggle attribute

- components/right-panel/consistent-evaluation-rubric.js
Rally: [US129073](https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F601565647541)
`legacy` attribute was being passed to the inline rubric component as a string instead of a boolean, which was forcing the legacy experience on for all instances of grading mode
> fix: bind inline rubrics revamp flag to boolean attribute

- components/left-panel/discussions/consistent-evaluation-discussion-evidence-body.js
- lang/en.js
Discussion post titles will now read "`{postTitle} (opens in a new tab)`" for screen-reader users
> ♿️ Add aria label for discussions link

- demo/consistent-evaluation-rubrics.html
- demo/data/rubric/198/assessment/8.json
- demo/data/rubric/198/assessment/8/stats.html
- package-lock.json
- package.json
- test/perceptual/data/rubric/198/assessment/8.json
- test/perceptual/data/rubric/198/assessment/8/stats.html
This updates the rubric result to include the statistics link. This was added recently. This also updates to latest `d2l-rubric` and `@brightspace-ui/core` and adds `--preserve-symlinks` to demo runner so you can `npm link` in stuff if needed for testing.
> Update rubric assessment demo/test data

- components/left-panel/discussions/consistent-evaluation-evidence-discussion.js
Fixes [US129373](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F602338301313)
Missed resetting a variable when filters are cleared, so the displayed posts weren't getting updated!
> US129373 - fixing clear filter bug

- components/left-panel/assignments/consistent-evaluation-evidence-file.js
[DE44005](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fdefect%2F601856333077&fdp=true?fdp=true): Assignment>20.21.5 & 20.21.6>Maximize Annotations window not responding
Add back src attribute that was removed here: https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/commit/2d92e7bfdd09a410bf793931247ebb23194900e2#diff-8d6e4a8c5b24f138e7dc1b963ca992db596d7c3bf70713bf55cd6886ba47c207
Jamie and I chatted re: context of this, and I followed up with Dale and Megan. They're comfortable with proceeding.
> DE44005 - Fix annotations full screen

- components/left-panel/discussions/consistent-evaluation-evidence-discussion.js
Fixes [US129385 ](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F602368931165) by waiting until `_getDiscussionPostEntities()` finishes fetching the discussion posts before trying to render the table!
> US129385 - solving discussions table flicker on load

- components/left-panel/discussions/consistent-evaluation-evidence-discussion.js
[US129155](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F601750512757)
- Fixes the issue where the post scores would not be synced up with the overall grade score (this is because we stopped re-fetching `discussionPostList` is updated)
> Fix de-sync between scored post and overall grade

- components/consistent-evaluation-page.js
- components/consistent-evaluation.js
#588 re-introduced a bug where saving evaluation would populate discussion post scores with old grades
`_refreshDiscussionPosts()` was periodically fetching the old `post-scores` due to a race condition with our transient-save. Fixed this by updating the discussion list `on-transient-save`  instead of re-fetching
> Fix: saving evaluation would populate discussion post scores with old grades
