BrightspaceHypermediaComponents/consistent-evaluation

components/consistent-evaluation-page.js, components/consistent-evaluation-secondary-block.js, components/consistent-evaluation.js
wrapping the elements that @cbusmand2l added in her right panel PR
=> adding secondary blocks around components

components/consistent-evaluation-html-editor.js, components/consistent-evaluation-page.js, components/consistent-evaluation-rubric.js, demo/consistent-evaluation-html-editor.html, demo/consistent-evaluation-rubrics.html, demo/index.html
Added demo pages for rubrics and html-editor and fixed improper imports
=> Adding more demo pages

components/consistent-evaluation-page.js, components/consistent-evaluation.js, components/controllers/ConsistentEvaluationHrefController.js, components/controllers/FooterController.js, components/controllers/constants.js, components/footer/consistent-evaluation-footer.js, package-lock.json, package.json, test/ConsistentEvaluationHrefController.test.js, test/FooterController.test.js
Creating this PR to make that footer interact with the right panel. This PR implements:
- the next student button now reloads the entire context and iterates forward
- the publish and retract buttons now work and will appear depending on the current context
- there are now unit tests for the href and footer controllers
=> wiring up top-level component and created tests for href and footer controllers

demo/consistent-evaluation-right-panel-visual.html, demo/index.html
=> adding a demo for the right panel

demo/consistent-evaluation-grade-result.html, demo/consistent-evaluation-outcomes.html, demo/consistent-evaluation-rubrics.html
There were some issues rendering some of the demos in smaller divs to show their responsiveness. This PR fixes that...
=> fixing the responsive demos

components/right-panel/consistent-evaluation-grade-result.js
Just adding some temporary logging so that it makes Peggy's life easier when testing on quad
=> adding additional event logging for debugging purposes

components/left-panel/consistent-evaluation-submission-item.js, components/left-panel/consistent-evaluation-submissions-page.js, components/right-panel/consistent-evaluation-feedback-presentational.js, components/right-panel/consistent-evaluation-feedback.js, components/right-panel/consistent-evaluation-right-panel.js
Cleaned up unused attributes, changed rich-text-editor-config to property name
=> Best Practices Name Tweaks / Cleanup

components/consistent-evaluation.js, package-lock.json
[US118767](https://rally1.rallydev.com/#/detail/userstory/406816818776?fdp=true): [Evidence] Remove 1230px width page margin restriction
Full page width:
=> force full page width

components/consistent-evaluation-page.js, components/left-panel/consistent-evaluation-left-panel.js
Fix for issue from this thread: https://d2l.slack.com/archives/CSL64JP9U/p1595852000335200
=> fix scrolling

components/left-panel/consistent-evaluation-submission-item.js, components/left-panel/consistent-evaluation-submissions-page.js, demo/consistent-evaluation-submissions-page.html, locales/en.js, package-lock.json, package.json
Related to user story: https://rally1.rallydev.com/#/detail/userstory/408052509400?fdp=true
=> remove moment import from submissions page

components/left-panel/consistent-evaluation-evidence-file.js, components/left-panel/consistent-evaluation-evidence-text.js, components/left-panel/consistent-evaluation-evidence-top-bar.js, components/left-panel/consistent-evaluation-left-panel.js, components/left-panel/consistent-evaluation-submission-item.js, locales/en.js, package-lock.json
Adds the option to show a full text submission in the left panel by clicking the "View full submisson" option in the submission's `...` menu.
=> Show Text Evidence

components/right-panel/consistent-evaluation-right-panel-block.js
Worked with Dan to get proper alignment & typography of headers in the right panel (match the headings to "attachments")
=> Fix right panel headers

components/right-panel/consistent-evaluation-feedback-presentational.js, components/right-panel/consistent-evaluation-right-panel-block.js
Fix spacing in the right panel:
- vertical spacing
- padding to the right side of components
Related to [US118766](https://rally1.rallydev.com/#/294005552584d/custom/236803223728?detail=%2Fuserstory%2F406815573864)
=> Fix right panel spacing

components/right-panel/consistent-evaluation-feedback-presentational.js
Related to [US120640](https://rally1.rallydev.com/#/388869855380d/dashboard?detail=%2Fuserstory%2F436813346276)
=> Fix bug where feedback does not update on iteration

components/header/d2l-consistent-evaluation-lcb-user-context.js, components/header/d2l-consistent-evaluation-learner-context-bar.js, package-lock.json
[US119916](https://rally1.rallydev.com/#/detail/userstory/422748376172?fdp=true): [LCB] [User Context] Create sub-component for user context within LCB
Profile image:
No profile image:
=> Update lcb to display profile image and use user href

components/header/d2l-consistent-evaluation-lcb-file-context.js, package-lock.json
SC showing truncation in dropdown: 
SC showing truncation on selection:
=> Truncate file name in file context and keep extension

components/consistent-evaluation-page.js, components/consistent-evaluation.js, components/controllers/ConsistentEvaluationHrefController.js, components/controllers/constants.js, components/header/d2l-consistent-evaluation-lcb-file-context.js, components/header/d2l-consistent-evaluation-learner-context-bar.js, components/left-panel/consistent-evaluation-submissions-page.js, karma.conf.js, karma.sauce.conf.js, test/ConsistentEvaluationHrefController.test.js, test/global-variables-for-test.js, test/global-variables.js
Added a subtle button to indicate how late the submission is, the button will open a special-access dialog for that particular use
=> Handle late submission in LCB

components/consistent-evaluation-page.js, components/left-panel/consistent-evaluation-evidence-file.js, package-lock.json, package.json
In the name of smaller PRs, this is just a small refactor I want to get in before actually handing annotations updates.
=> Refactor before handling annotations updates

components/consistent-evaluation-page.js, components/right-panel/consistent-evaluation-right-panel.js
This is the only way I could get it to work without making changes outside of our own component
=> - Fixing issue with iterator navigation and rubric grade sync

components/consistent-evaluation-page.js
=> - Adding resizable property to template page

components/consistent-evaluation-page.js
quick cleanup PR.
1. rename the dialog now that there are 2 dialogs. basically i just added `unsavedChanges` to the variable names.
2. delete `evaluationState` which was unused, and a bit dangerous (caching stale data)
=> delete unused evaluationstate. rename dialog

components/right-panel/consistent-evaluation-right-panel-block.js, components/right-panel/consistent-evaluation-right-panel.js
[US122407](https://rally1.rallydev.com/#/detail/userstory/456565213984?fdp=true): Alignment work in Mobile view
Updated:
=> design updates to mobile adaptive

components/left-panel/consistent-evaluation-evidence-file.js
This is clearly a bit too fragile, might be worth revisiting later.
=> - Fix issue with double scroll bar

components/right-panel/consistent-evaluation-outcomes.js
=> Outcomes not displaying summary information

components/consistent-evaluation-page.js
classic case of making a change right before pushing and not testing 🤦
=> wait for async result

test/perceptual/consistent-evaluation-footer.visual-diff.js, test/perceptual/consistent-evaluation-grade-result.visual-diff.js, test/perceptual/consistent-evaluation-header-nav-bar.visual-diff.js, test/perceptual/consistent-evaluation-outcomes.visual-diff.js, test/perceptual/consistent-evaluation-right-panel.visual-diff.js, test/perceptual/consistent-evaluation-rubric.visual-diff.js, test/perceptual/consistent-evaluation.visual-diff.js
As per this thread: https://d2l.slack.com/archives/C0PHG3QB0/p1606252808231200
=> Add required logic so that tests can run

components/header/d2l-consistent-evaluation-learner-context-bar.js
No functional changes, just cleaning up the console error
=> - Fixing console error when rendering skeleton

components/left-panel/consistent-evaluation-submissions-page.js
This PR contains 2 changes:
1. Use cache for submission entities
* This consists of the single line boolean change on line 181
2. Assume flag/read worked so we can update the UI instantly
* The rest of the diff is this change
The code change is small but the ramifications are complex. First let's talk about using the cache for submission entities. At first glance it looks wrong, since we're always fetching from cache but never invalidating the cache. It turns out we are implicitly updating the cache here:
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/blob/master/components/left-panel/consistent-evaluation-submissions-page.js#L226
What's happening there is `this._submissionEntities[i].entity` is actually the exact same reference that is being used by …
=> Hit cache everytime for submissions-page. Assume read/flag worked

components/right-panel/consistent-evaluation-popup-rubric.js, lang/en.js
[US123683](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fuserstory%2F478450711396&fdp=true?fdp=true): [Right Panel] Rubric pop out - title should be Assess Rubric - [student name]
=> add users name to rubrics

components/right-panel/consistent-evaluation-rubric.js
Thanks, @jmurray-d2l this worked exactly as intended.
=> close rubrics popout on back to submissions

components/right-panel/consistent-evaluation-rubric.js
No reason to reload the popup if its already open, just focus it
=> - Set focus to popup window if it is already open

components/header/d2l-consistent-evaluation-learner-context-bar.js, components/helpers/converterHelpers.js, components/left-panel/consistent-evaluation-submissions-page.js, components/right-panel/consistent-evaluation-feedback-presentational.js, components/right-panel/consistent-evaluation-outcomes.js, components/right-panel/consistent-evaluation-popup-rubric.js, components/right-panel/consistent-evaluation-right-panel.js
Reduce repetitive converter code
=> Extract href converter logic to helper

components/consistent-evaluation-dialogs.js, components/consistent-evaluation-page.js
Note to self merge after https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/267
=> US124085/mbosilj move unsaved changes dialog.

components/controllers/ConsistentEvaluationHrefController.js, components/header/consistent-evaluation-user-profile-card.js, components/header/d2l-consistent-evaluation-lcb-user-context.js, test/ConsistentEvaluationHrefController.test.js
Removed tagline from user-profile-card
Added profile pic and display name
=> Add profile pic and display name to user-profile-card

components/header/d2l-consistent-evaluation-lcb-user-context.js, package-lock.json
This fixes the problem where the profile card wouldn't disappear when mousing away from it and adds an invisible area between the user context and the profile card that will keep it open. The area is as small as it could be made, and dismisses the card on click so it won't block access to other elements.
=> Fix profile card not disappearing when mousing away

components/left-panel/consistent-evaluation-submission-item.js
=> US124816/mbosilj make profile card appear over more button.

components/header/consistent-evaluation-user-profile-card.js, components/header/d2l-consistent-evaluation-lcb-user-context.js
Add keyboard accessibility to user-profile-card
Tabbing opens up the card and the last tab in the card will close it and tab into the submissions dropdown
=> Add ability to tab into user-profile-card

components/consistent-evaluation-page.js, components/consistent-evaluation.js, components/controllers/ConsistentEvaluationHrefController.js, components/controllers/constants.js, components/header/consistent-evaluation-user-profile-card.js, components/header/d2l-consistent-evaluation-lcb-user-context.js, components/header/d2l-consistent-evaluation-learner-context-bar.js, test/ConsistentEvaluationHrefController.test.js
On group drop-down menu click: 
- Opens email and instant messaging in new windows
- Opens view members in a legacy dialog
Add unit tests for `getGroupInfo`
=> Add group actions

components/header/d2l-consistent-evaluation-lcb-user-context.js
We want the updated lifecycle method here because the first few updates, groupInfo is still null as we wait for a response from the api.
=> showing instant message button only if href is present

components/right-panel/consistent-evaluation-rubric.js
=> US125103/mcbosilj fix open rubrics icon in rtl.

components/controllers/ConsistentEvaluationHrefController.js, components/controllers/constants.js, test/ConsistentEvaluationHrefController.test.js
This now goes to assignments portion of user progress as expected
=> use new user progress path

components/header/d2l-consistent-evaluation-lcb-user-context.js
=> Do not render group drown down option if API path is not defined

components/left-panel/consistent-evaluation-submission-item.js
This reverts commit 169c16781be766ec06e3d6549794a563dc025d5a.
=> Revert "US124816/mbosilj make profile card appear over more button."

components/consistent-evaluation-page.js, components/consistent-evaluation.js, components/controllers/ConsistentEvaluationHrefController.js, components/controllers/constants.js, components/right-panel/consistent-evaluation-right-panel.js, test/ConsistentEvaluationHrefController.test.js
It will not show the option if there is no path.
=> Add edit activity button to right-panel overflow menu

.github/workflows/Checklist.yml
Add GitHub-action to comment on opened PR with consistent-eval checklist
=> Add checklist on CE pull requests

components/controllers/ConsistentEvaluationController.js, components/controllers/constants.js, components/header/d2l-consistent-evaluation-lcb-file-context.js, components/header/d2l-consistent-evaluation-lcb-user-context.js, components/left-panel/consistent-evaluation-left-panel.js, components/right-panel/consistent-evaluation-grade-result.js, components/right-panel/consistent-evaluation-right-panel.js, package-lock.json, package.json
Just want to plug this logging client in and start filling up the dev dashboard with events.
=> use the new logging client

components/helpers/consistent-eval-telemetry.js
Will wait for CE to come back to green before I merge this
=> Adds the user agent

components/consistent-evaluation-page.js, components/controllers/ConsistentEvaluationController.js, components/controllers/constants.js, components/left-panel/discussions/consistent-evaluation-discussion-evidence-body.js, components/left-panel/discussions/consistent-evaluation-discussion-post-page.js, components/left-panel/discussions/consistent-evaluation-discussion-post-score.js, test/ConsistentEvaluationController.test.js
Still need to double check that syncing works with rubrics and fix it if not
Also will make it look nicer when we have a table to put it in :p
=> US125732/add save score action.

components/consistent-evaluation-page.js, components/helpers/rubricGradeSyncHelpers.js, package-lock.json, package.json, test/helpers/rubricGradeSyncHelpers.test.js, test/perceptual/consistent-evaluation-grade-result.visual-diff.html
Note This PR also has to update the grade-result
=> DE43073/pass empty string instead of none grade.

components/controllers/constants.js, components/left-panel/discussions/consistent-evaluation-discussion-evidence-body.js, components/left-panel/discussions/consistent-evaluation-discussion-post-page.js
Open's post location when user clicks the posts title.
Note the links for posts aren't working right now. The links for replies seem to be fine!
=> Add postHref to title.

components/left-panel/discussions/consistent-evaluation-discussion-post-page.js, components/left-panel/discussions/consistent-evaluation-evidence-discussion.js
Move indicator to `consistent-evaluation-discussion-post-page` .
=> US126243/update indicator with filtered data.

components/consistent-evaluation-page.js, components/controllers/ConsistentEvaluationHrefController.js, components/right-panel/consistent-evaluation-popup-rubric.js, components/right-panel/consistent-evaluation-right-panel.js, components/right-panel/consistent-evaluation-rubric.js, test/ConsistentEvaluationHrefController.test.js
Note still need to do some testing on discussions popout rubrics but still wanted to get some eyes on this
=> US127295/remove console error when grading rubrics.

components/controllers/ConsistentEvaluationHrefController.js, components/right-panel/consistent-evaluation-rubric.js, lang/en.js, test/perceptual/consistent-evaluation-popup-rubric.visual-diff.js, test/perceptual/consistent-evaluation-right-panel.visual-diff.js, test/perceptual/consistent-evaluation-rubric.visual-diff.js
(cherry picked from commit a83d7fc7a6b889e96216ffbda2ead10207e4113a)
=> DE43451 - Handling unable to get rubric assessor

components/left-panel/discussions/consistent-evaluation-discussion-evidence-body.js
=> Indicate what the list is of for clarity - attachment

components/left-panel/discussions/consistent-evaluation-discussion-evidence-body.js
Before (Entire row is clickable)
Now (Only the title is clickable)
=> US128171 - Discussion - Fix user topic link clickable area

package-lock.json, package.json
=> use new profile card version

components/left-panel/discussions/consistent-evaluation-discussion-post-page.js
The div containing the table was stretching off screen.
=> Adjust Discussions Table to Fit on Mobile

components/consistent-evaluation.js, lang/en.js
Fixes [US128203 ](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F604652665668) by setting a page title for discussions (not just assignments).
=> US128203 Read page title when advancing to next student (discussions)

components/consistent-evaluation-page.js, components/consistent-evaluation.js, components/right-panel/consistent-evaluation-right-panel.js, components/right-panel/consistent-evaluation-rubric.js
https://rally1.rallydev.com/#/57732444928d/dashboard?detail=%2Fportfolioitem%2Ffeature%2F486538953568
=> Pass new rubric tile flag attribute to d2l-rubric

components/left-panel/assignments/consistent-evaluation-evidence-file.js, karma.sauce.conf.js
=> add back src attribute

components/consistent-evaluation-page.js, components/consistent-evaluation.js, components/right-panel/consistent-evaluation-right-panel.js, components/right-panel/consistent-evaluation-rubric.js
Cert copy of [#565](https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/565)
=> [Cert 20.21.7] Propagate new inline rubric tile flag to d2l-rubric

components/consistent-evaluation-page.js, components/consistent-evaluation.js
Fixes [US128203 ](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F604652665668) - second time's the charm!
=> US128203 - Announce page title when iterating students

components/consistent-evaluation-page.js, components/consistent-evaluation.js, components/right-panel/consistent-evaluation-right-panel.js, components/right-panel/consistent-evaluation-rubric.js
Rally: [US124186](https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F485864539352)
=> US124186 - Propagate rubric-overall-score flag into CE rubric component

package-lock.json, package.json
Backporting [this update in CE](https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/578) with [these changes from the Profile Card](https://github.com/BrightspaceUILabs/user-profile-card/commit/593c6ce90b77ef9915d90a1b28ae9561bc55bc61)
=> ⬆️ Backport Profile card fix
